// Package consentv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.3 DO NOT EDIT.
package consentv1

import (
	externalRef0 "github.com/absurdlab/tiga-sdk/tiga-go-sdk/apiv1/common"
)

// ConsentCallback defines model for ConsentCallback.
type ConsentCallback struct {
	// List of scopes granted by the user.
	GrantedScopes []string `json:"granted_scopes,omitempty" yaml:"granted_scopes,omitempty"`
}

// ConsentRequest defines model for ConsentRequest.
type ConsentRequest struct {
	// ClientInfo contains public client information that can be used to visually identity the client.
	Client externalRef0.ClientInfo `json:"client,omitempty" yaml:"client,omitempty"`
	Links  externalRef0.Links      `json:"links,omitempty" yaml:"links,omitempty"`

	// Optional array containing prompt parameters. This fields exists only for backward compatibility
	// purposes but is no longer useful. The consent prompts processing capability is moved to the Tiga server.
	// When prompts contains PromptConsent, all requested scopes are always included in this request and requires
	// user approval, regardless of previous grant records. When prompts contains PromptNone, the consent
	// interaction will not happen. By default, only the un-granted scopes are included in this request.
	// For the sake of the identity provider, it is fine to ignore the prompts and just process the list of
	// scopes included in this request.
	Prompts []string `json:"prompts,omitempty" yaml:"prompts,omitempty"`

	// List of scope that reuqires user consent.
	Scopes []string `json:"scopes,omitempty" yaml:"scopes,omitempty"`

	// Subject identifier for the user whose consent is needed.
	Sub string `json:"sub,omitempty" yaml:"sub,omitempty"`

	// Optional list of preferred UI locales.
	UiLocales []string `json:"ui_locales,omitempty" yaml:"ui_locales,omitempty"`
}

// SessionId defines model for sessionId.
type SessionId string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse externalRef0.ErrorResponse

// CallbackConsentFailureJSONBody defines parameters for CallbackConsentFailure.
type CallbackConsentFailureJSONBody externalRef0.ErrorCallback

// CallbackConsentSuccessJSONBody defines parameters for CallbackConsentSuccess.
type CallbackConsentSuccessJSONBody ConsentCallback

// CallbackConsentFailureJSONRequestBody defines body for CallbackConsentFailure for application/json ContentType.
type CallbackConsentFailureJSONRequestBody CallbackConsentFailureJSONBody

// CallbackConsentSuccessJSONRequestBody defines body for CallbackConsentSuccess for application/json ContentType.
type CallbackConsentSuccessJSONRequestBody CallbackConsentSuccessJSONBody
