// Package loginv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.3 DO NOT EDIT.
package loginv1

import (
	externalRef0 "github.com/absurdlab/tiga-sdk/tiga-go-sdk/apiv1/common"
)

// AuthenticationCallback defines model for AuthenticationCallback.
type AuthenticationCallback struct {
	// Authentication context class reference.
	Acr string `json:"acr"`

	// A list of authentication methods applied.
	Amr []string `json:"amr"`

	// Unix timestamp for time of authentication.
	AuthTime int64 `json:"auth_time"`

	// Identifier of the user session as a result of authentication.
	Sid string `json:"sid"`

	// Subject identifier of the authenticated user.
	Sub string `json:"sub"`
}

// AuthenticationRequest defines model for AuthenticationRequest.
type AuthenticationRequest struct {
	// Optional array of requested ACR values for the authentication.
	AcrValues []string `json:"acr_values"`

	// ClientInfo contains public client information that can be used to visually identity the client.
	Client externalRef0.ClientInfo `json:"client"`
	Links  externalRef0.Links      `json:"links"`

	// Optional login hint parameter to pass on to the identity provider.
	LoginHint string `json:"login_hint"`

	// Optional max_age parameter.
	MaxAge *int64 `json:"max_age,omitempty"`

	// Optional array containing prompt parameters.
	Prompts []string `json:"prompts"`

	// Optional subject identifier to request authentication for.
	SubHint string `json:"sub_hint"`

	// Optional list of preferred UI locales.
	UiLocales []string `json:"ui_locales"`
}

// SessionId defines model for sessionId.
type SessionId string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse externalRef0.ErrorResponse

// CallbackAuthenticationFailureJSONBody defines parameters for CallbackAuthenticationFailure.
type CallbackAuthenticationFailureJSONBody externalRef0.ErrorCallback

// CallbackAuthenticationSuccessJSONBody defines parameters for CallbackAuthenticationSuccess.
type CallbackAuthenticationSuccessJSONBody AuthenticationCallback

// CallbackAuthenticationFailureJSONRequestBody defines body for CallbackAuthenticationFailure for application/json ContentType.
type CallbackAuthenticationFailureJSONRequestBody CallbackAuthenticationFailureJSONBody

// CallbackAuthenticationSuccessJSONRequestBody defines body for CallbackAuthenticationSuccess for application/json ContentType.
type CallbackAuthenticationSuccessJSONRequestBody CallbackAuthenticationSuccessJSONBody
